//  RMIT University Vietnam
//   Course: COSC2767 Systems Deployment and Operations
//   Semester: 2022B
//   Assessment: Assignment 2
//   Author: Truong Adam Nhat Anh
//   ID: s3926016
//   Created  date: 27/12/2023
//   Last modified: 29/12/2023
//   Acknowledgement: 
pipeline {
    agent any
    tools {
        maven 'maven 3.9.6'
        git 'Git'
    }
    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/adamtruong/COSC2767_Assignment2_Jekins_Docker_s3926016.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Publish Dockerfile Over SSH'){
            steps {
                sshPublisher(publishers: [sshPublisherDesc(configName: 'Docker-Admin', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '', remoteDirectorySDF: false, removePrefix: '', sourceFiles: 'Dockerfile')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }
        stage('Publish Over SSH'){
            steps {
                sshPublisher(publishers: [sshPublisherDesc(configName: 'Docker-Admin', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '''cd /home/dockeradmin
                docker build -t tomcat .
                docker stop tomcat-container
                docker rm tomcat-container
                docker run -d --name tomcat-container -p 8081:8080 tomcat''', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '', remoteDirectorySDF: false, removePrefix: 'target', sourceFiles: 'target/*.war')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }
    }
}